const GROUPS = {
  spindle: ["Шпиндель", "#49a5ff", "73,165,255", "spindle", "Управление вращением главного шпинделя и скоростью резания.", "Перед запуском убедись, что заготовка надёжно зажата, а зона вращения свободна."],
  chuck: ["Патрон", "#4ee8f2", "78,232,242", "chuck", "Зажим и разжим заготовки в патроне станка.", "Разжимать патрон можно только при полностью остановленном шпинделе."],
  turret: ["Револьвер", "#ff9d3d", "255,157,61", "turret", "Ручная индексация, зажим и обслуживание револьверной головки.", "Может привести к потере позиции инструмента. Проверь безопасное положение перед разжимом."],
  coolant: ["СОЖ", "#78ef62", "120,239,98", "coolant", "Включение и отключение подачи охлаждающей жидкости или воздуха.", "Проверь направление сопла и закрытие защитной двери."],
  tailstock: ["Задняя бабка", "#f15b99", "241,91,153", "tailstock", "Подвод и отвод задней бабки для поддержки длинной заготовки.", "Перед перемещением проверь свободный ход и положение инструмента."],
  thread: ["Резьба", "#48cef2", "72,206,242", "thread", "Нарезание резьбы резцом или метчиком с заданным шагом.", "Неверный шаг, подача или направление могут сломать инструмент и повредить деталь."],
  feed: ["Подача", "#48dbe6", "72,219,230", "feed", "Настройка режима подачи и характера движения по траектории.", "Проверь единицы подачи: мм/мин и мм/об — это разные режимы."],
  correction: ["Коррекция", "#ffd23f", "255,210,63", "correction", "Компенсация радиуса, положения и геометрии инструмента.", "Неверная сторона коррекции может направить инструмент внутрь контура."],
  offset: ["Нулевые смещения", "#b76cff", "183,108,255", "offset", "Выбор и управление системой координат заготовки.", "Перед циклом проверь активное нулевое смещение и фактический ноль детали."],
  path: ["Траектория", "#50a9ff", "80,169,255", "path", "Линейные, круговые и сглаженные перемещения инструмента.", "Проверь координаты конечной точки, плоскость и безопасный подвод."],
  program: ["Программа", "#8aa9ff", "138,169,255", "program", "Остановка, завершение, перемотка и вызов подпрограмм.", "Убедись, что продолжение или повторный запуск программы безопасен."],
  tool: ["Инструмент", "#f2b84b", "242,184,75", "tool", "Смена инструмента и работа с измерительным щупом.", "Перед движением проверь свободное пространство и корректный номер инструмента."],
  plane: ["Плоскость", "#49d9b3", "73,217,179", "plane", "Выбор рабочей плоскости для интерполяции и коррекции.", "Неверная плоскость изменит направление дуг и работу коррекции."],
  speed: ["Скорость", "#ffbf47", "255,191,71", "speed", "Режимы постоянной скорости резания и ограничения оборотов.", "При G96 обязательно задавай безопасное ограничение максимальных оборотов."],
  brake: ["Тормоз", "#ff6b62", "255,107,98", "brake", "Фиксация и освобождение главного шпинделя.", "Не включай тормоз на вращающемся шпинделе."],
  transform: ["Трансформации", "#ba72ff", "186,114,255", "transform", "Поворот, масштабирование, зеркалирование и преобразование координат.", "Проверь активную систему координат и отменяй трансформацию после обработки."],
};

const RAW_M = [
  ["M00","Останов программы","Program stop","program"],
  ["M01","Выборочный останов программы","Optional stop","program"],
  ["M02","Завершение программы","End of program","program"],
  ["M03","Вращение шпинделя вперёд","Spindle CW","spindle"],
  ["M04","Реверс шпинделя","Spindle CCW","spindle"],
  ["M05","Остановка шпинделя","Spindle stop","spindle"],
  ["M06","Автоматическая смена инструмента","Auto tool change","tool"],
  ["M07","Подача воздуха / туман","Mist ON","coolant"],
  ["M08","СОЖ включена","Coolant ON","coolant"],
  ["M09","СОЖ выключена","Coolant OFF","coolant"],
  ["M10","Зажим патрона","Chuck clamp","chuck"],
  ["M11","Разжим патрона","Chuck unclamp","chuck"],
  ["M24","Выдвинуть щуп инструмента","Tool setter extend","tool"],
  ["M25","Убрать щуп инструмента","Tool setter retract","tool"],
  ["M28","Отмена жёсткого нарезания резьбы","Rigid tapping cancellation","thread"],
  ["M29","Жёсткое нарезание резьбы","Rigid tapping","thread"],
  ["M30","Конец программы и возврат в начало","Program rewind","program"],
  ["M50","Конвейер стружки вперёд","Chip conveyor forward","feed"],
  ["M60","Тормоз шпинделя включён","Spindle brake ON","brake"],
  ["M61","Тормоз шпинделя выключен","Spindle brake OFF","brake"],
  ["M75","Револьвер разжим","Turret unclamp","turret"],
  ["M76","Револьвер зажим","Turret clamp","turret"],
  ["M78","Задняя бабка вперёд","Tailstock advance","tailstock"],
  ["M79","Задняя бабка назад","Tailstock retract","tailstock"],
  ["M80","Маховик шпинделя включён","Spindle handwheel control ON","spindle"],
  ["M81","Маховик шпинделя выключен","Spindle handwheel control OFF","spindle"],
  ["M98","Вызов подпрограммы","Calling of subprogram","program"],
  ["M99","Возврат из подпрограммы","End of subprogram","program"],
];

const RAW_G = [
  ["G0","Быстрое перемещение","Rapid traverse","path"],
  ["G1","Линейная интерполяция","Linear interpolation","path"],
  ["G2","Круговая интерполяция по часовой","Clockwise circular interpolation","path"],
  ["G3","Круговая интерполяция против часовой","Counterclockwise circular interpolation","path"],
  ["CIP","Дуга через промежуточную точку","Circular interpolation via intermediate point","path"],
  ["G70","Дюймовая система: геометрия","Activate inch system (geometric data)","offset"],
  ["G71","Метрическая система: геометрия","Activate metric system (geometric data)","offset"],
  ["G700","Дюймовая система: геометрия + процесс","Activate inch system (geometric + process data)","offset"],
  ["G710","Метрическая система: геометрия + процесс","Activate metric system (geometric + process data)","offset"],
  ["G90","Абсолютное программирование","Absolute dimensioning","offset"],
  ["G91","Инкрементальное программирование","Incremental dimensioning","offset"],
  ["G17","Рабочая плоскость X/Y","Select X/Y working plane","plane"],
  ["G18","Рабочая плоскость Z/X","Select Z/X working plane","plane"],
  ["G19","Рабочая плоскость Y/Z","Select Y/Z working plane","plane"],
  ["G93","Подача в обратном времени","Inverse time feed rate","feed"],
  ["G94","Линейная подача, мм/мин","Linear feed rate","feed"],
  ["G95","Подача на оборот, мм/об","Rotational feed rate","feed"],
  ["G96","Постоянная скорость резания","Constant cutting speed","speed"],
  ["G961","Постоянная скорость резания, линейная подача","Constant cutting speed (linear feed mode)","speed"],
  ["G962","Постоянная скорость, линейная + оборотная подача","Constant cutting speed (linear + rotational feed)","speed"],
  ["G97","Отмена постоянной скорости резания","Cancel constant cutting speed","speed"],
  ["G971","Отмена G96, линейная подача","Cancel constant cutting speed (linear feed)","speed"],
  ["G972","Отмена G96, линейная/оборотная подача","Cancel constant cutting speed (linear/rotational feed)","speed"],
  ["G973","Отмена G96 без ограничения скорости","Cancel constant cutting speed (no speed limit)","speed"],
  ["G25","Нижний предел оборотов шпинделя","Spindle speed lower limit","speed"],
  ["G26","Верхний предел оборотов шпинделя","Spindle speed upper limit","speed"],
  ["G40","Отмена коррекции радиуса","Cancel tool radius compensation","correction"],
  ["G41","Коррекция радиуса слева от контура","Tool radius compensation left","correction"],
  ["G42","Коррекция радиуса справа от контура","Tool radius compensation right","correction"],
  ["G140–G143","Плавный подвод и отвод: базовый режим","Soft approach and retraction (basic)","path"],
  ["G147–G148","Плавный подвод и отвод: расширенный","Soft approach and retraction (extended)","path"],
  ["G247–G248","Плавный подвод и отвод: 2D","Soft approach and retraction (2D)","path"],
  ["G340–G341","Плавный подвод и отвод: 3D","Soft approach and retraction (3D)","path"],
  ["G347–G348","Плавный подвод: специальный инструмент","Soft approach (special tool mode)","path"],
  ["G460–G462","Расширенные стратегии отвода","Extended retraction strategies","path"],
  ["CUT2D","2.5D-коррекция: базовый режим","2 1/2 D tool offset (basic mode)","correction"],
  ["CUT2DD","2.5D-коррекция: режим глубины","2 1/2 D tool offset (depth mode)","correction"],
  ["CUT2DF","2.5D-коррекция: режим подачи","2 1/2 D tool offset (feed mode)","correction"],
  ["CUT2DFD","2.5D-коррекция: глубина + подача","2 1/2 D tool offset (depth + feed)","correction"],
  ["CUTCONON","Постоянная коррекция радиуса","Keep tool radius compensation constant","correction"],
  ["CUTCONOF","Отмена постоянной коррекции","Cancel constant tool radius compensation","correction"],
  ["G53","Подавление задаваемого и программного смещения","Suppress settable + programmable zero offset","offset"],
  ["G54–G59","Выбор нулевого смещения 1–6","Call 1st–6th settable zero offset","offset"],
  ["G500","Отключить текущее нулевое смещение","Close current settable zero offset","offset"],
  ["G507–G599","Выбор нулевого смещения 7–99","Call 7th–99th settable zero offset","offset"],
  ["G153","Подавить все нулевые смещения","Suppress all zero offsets","offset"],
  ["G60","Режим точного останова","Exact stop mode","path"],
  ["G601","Точный останов","Exact stop precise","path"],
  ["G602","Приблизительный точный останов","Exact stop coarse","path"],
  ["G603","Точный останов с буфером","Exact stop with buffer","path"],
  ["G64","Непрерывная работа по траектории","Continuous path mode","path"],
  ["G641–G646","Непрерывная траектория: уровни сглаживания","Continuous path mode (smoothing levels)","path"],
  ["G62","Замедление во внутреннем углу","Inner corner deceleration","path"],
  ["G621","Замедление во всех углах","All corner deceleration","path"],
  ["G450","Обход внешнего угла по дуге","External corner traversal (circular)","path"],
  ["G451","Обход внешнего угла под острым углом","External corner traversal (acute angle)","path"],
  ["G33","Резьба с постоянным шагом","Thread cutting with constant pitch","thread"],
  ["G34","Резьба с увеличивающимся шагом","Thread cutting with increasing pitch","thread"],
  ["G35","Резьба с уменьшающимся шагом","Thread cutting with decreasing pitch","thread"],
  ["G331","Жёсткое резьбонарезание вперёд","Rigid tapping forward","thread"],
  ["G332","Жёсткое резьбонарезание назад","Rigid tapping reverse","thread"],
  ["G63","Резьба с компенсирующим патроном","Tapping with compensation chuck","thread"],
  ["G335","Выпуклая резьба","Convex thread cutting","thread"],
  ["G336","Специальная выпуклая резьба","Special convex thread cutting","thread"],
  ["G110","Полярная точка от последней позиции","Polar reference point (last return position)","offset"],
  ["G111","Полярная точка от нуля заготовки","Polar reference point (workpiece zero)","offset"],
  ["G112","Полярная точка от последнего полюса","Polar reference point (last valid pole)","offset"],
  ["CFTCP","Постоянная подача по центру инструмента","Constant feed on tool center trajectory","feed"],
  ["CFC","Постоянная подача по контуру","Constant feed on contour","feed"],
  ["CFIN","Оптимизация подачи на вогнутом контуре","Constant feed on concave contour","feed"],
  ["G4","Пауза","Dwell time","program"],
  ["G74","Подход к опорной точке","Reference point approach","offset"],
  ["G75","Подход к фиксированной точке","Approaching a fixed point","offset"],
  ["G290","Переключение языка: режим 1","Switch language mode (Mode 1)","program"],
  ["G291","Переключение языка: режим 2","Switch language mode (Mode 2)","program"],
  ["G5","Косое врезание: режим 1","Oblique plunge-cutting (Mode 1)","path"],
  ["G7","Косое врезание: режим 2","Oblique plunge-cutting (Mode 2)","path"],
  ["PTP","Декартово перемещение точка-точка","Cartesian PTP travel","path"],
  ["PTPG0","PTP в режиме быстрого хода","Cartesian PTP travel in rapid traverse","path"],
  ["PTPWOC","PTP без контроля столкновений","PTP travel without collision control","path"],
  ["CTRANS","Грубое смещение трансформации","Coarse transformation offset","transform"],
  ["CFINE","Точное смещение трансформации","Fine transformation offset","transform"],
  ["TRAFOON","Включить преобразование координат","Activate coordinate transformation","transform"],
  ["TRAFOOF","Отключить преобразование координат","Deactivate coordinate transformation","transform"],
  ["TRANSMIT","Трансформация торца","Activate face end transformation","transform"],
  ["TRACYL","Трансформация цилиндрической поверхности","Activate cylinder surface transformation","transform"],
  ["TRAANG","Трансформация с программируемым углом","Transformation with programmable angle","transform"],
  ["ROT","Программируемый поворот","Programmable rotation","transform"],
  ["AROT","Дополнительный поворот","Additional programmable rotation","transform"],
  ["RPL","Задать угол поворота","Rotation angle setting","transform"],
  ["SCALE","Программируемое масштабирование","Programmable scaling","transform"],
  ["ASCALE","Дополнительное масштабирование","Additional programmable scaling","transform"],
  ["MIRROR","Программируемое зеркалирование","Programmable mirroring","transform"],
  ["AMIRROR","Дополнительное зеркалирование","Additional programmable mirroring","transform"],
  ["TOFRAME","Поворот фрейма по инструменту/детали","Frame rotation to align at tool or workpiece","transform"],
  ["TOROT","Поворот ориентации инструмента","Tool orientation rotation","transform"],
  ["PAROT","Параллельный поворот","Parallel rotation","transform"],
];

const M_CODES = RAW_M.map(([code,title,english,group]) => ({ code,title,english,group,type:"M" }));
const G_CODES = RAW_G.map(([code,title,english,group]) => ({ code,title,english,group,type:"G" }));
const ALL_CODES = [...M_CODES, ...G_CODES];
const EXTRA = {
  M75: {
    description: "Отпускание зажимного механизма револьвера. Позволяет вращать и индексировать револьвер при ручном управлении.",
    warning: "Может привести к потере позиции инструмента. Убедись, что инструмент безопасен перед разжимом.",
    use: "Используется для ручной индексации револьвера или смены инструмента."
  },
  M76: { description: "Фиксирует револьверную головку в выбранной позиции после ручной индексации." }
};

export { GROUPS, M_CODES, G_CODES, ALL_CODES, EXTRA };
